package pacifico.mvm.trailblaze.model.reports;

public enum ReportReason {
	COPYRIGHT_VIOLATION,
	DISCRIMINATORY_CONTENT,
	DISRUPTIVE_BEHAVIOR,
	FALSE_INFORMATION,
	FRAUDULENT_OR_DECEPTIVE_BEHAVIOR,
	IMPERSONATION,
	INAPPROPRIATE_BEHAVIOR,
	INAPPROPRIATE_CONTENT,
	SHARING_PERSONAL_INFORMATION,
	SPAM,
	OTHER
}